### ISSUE TITLE
route generator creates incorrect templateUrl in routes.ng.js file.

### ISSUE THREAD

**Issue by mjoldic** [ndxbxrme/generator-angular-meteor#1]
Occurs when creating a route with no model and list/details routes. Routes file contains incorrect templateUrl. It is missing the 'ng'.

[myProject] yo angular-meteor:route main  
If you are planning to create a model or list/detail views it is recommended you use a plural route name
? Where would you like to create this route? /client
? Is this a protected route? No
? Would you like to make List/Details routes? No
? Would you like to create a Model? No
   create main.styl
   create main.controller.ng.js
   create main.routes.ng.js
   create main.view.ng.html

main.routes.ng.js:
'use strict'

angular.module('myProject')
.config(function($stateProvider) {
  $stateProvider
  .state('main', {
    url: '/main',
    templateUrl: 'client/main/main.view.html',
    controller: 'MainCtrl'
  });
});

**Comment by ndxbxrme** [comment]
fixed

**Comment by mjoldic** [comment]
awesome thanks! :-)

**Comment by yobre** [comment]
hi @ndxbxrme where have u fix the bug? Not in master, it seems.
Thanks
