### ISSUE TITLE
switch to $scope.$meteorCollection and $meteorObject ?

### ISSUE THREAD

**Issue by agung-wete** [ndxbxrme/generator-angular-meteor#10]
As official doc says (http://angular-meteor.com/api/meteorCollection and http://angular-meteor.com/api/meteorObject), it is the "recommended ways".
What do you think ?

**Comment by ndxbxrme** [comment]
I'm down with that
I'll have a go at it this evening, unless you fancy doing it...

**Comment by ndxbxrme** [comment]
Done (v0.13.0)
Give it a test and let me know

**Comment by agung-wete** [comment]
:+1: , thank you
