### ISSUE TITLE
Pagination stop working after go to detail page

### ISSUE THREAD

**Issue by agung-wete** [ndxbxrme/generator-angular-meteor#11]
its issue from tutorial http://angular-meteor.com/tutorials/angular1/search-sort-pagination-and-reactive-vars

assuming 'cat' is my route : 

in cat-detail.controller.ng.js change 
`$meteor.subscribe('cat');`
TO
`$scope.$meteorSubscribe('cat);`

from [doc](http://angular-meteor.com/api/subscribe) : 

> Calling $scope.$meteorSubscribe will automatically stop the subscription when the scope is destroyed.

also in cat-list.controller.ng.js, there's `$meteor.subscribe`, do we also need to change to     `$scope.$meteorSubscribe` ?

**Comment by ndxbxrme** [comment]
Nice catch.  Looking into it now

**Comment by ndxbxrme** [comment]
Give v0.13.1 a try

**Comment by agung-wete** [comment]
thank you
