### ISSUE TITLE
Feature: Back to same list page after go to detail page

### ISSUE THREAD

**Issue by agung-wete** [ndxbxrme/generator-angular-meteor#12]
If we back to list page from detail page, the list always start from page 1 (related #11). With this mod, we can back to same page as before.

cat-list.controller.ng.js

```
//page marker
$meteor.session('kupatCounter').bind($scope, 'page');
```

and

kupat-list.view.ng.html

```
<li dir-paginate="cat in cat | itemsPerPage: perPage" total-items="catCount.count" current-page="page">
```

**Comment by ndxbxrme** [comment]
I'll give it a try

**Comment by ndxbxrme** [comment]
Works well.  Thanks for the suggestion.  Check out v0.13.2

**Comment by agung-wete** [comment]
thank you
