### ISSUE TITLE
Run 'meteor add' in one go

### ISSUE THREAD

**Issue by agung-wete** [ndxbxrme/generator-angular-meteor#14]
How about run 'meteor add' command in one go? i do testing, its quite fast than do it one by one

**Comment by ndxbxrme** [comment]
Writing the package names directly into /meteor/packages and letting meteor grab them when it needs them would probably be even faster.  It is something I've thought about for a while but it hasn't been slow enough to annoy me into doing anything about it.  I'll give it some more thought...

**Comment by agung-wete** [comment]
its slower than manually do `meteor create` and `meteor add ...`

**Comment by ndxbxrme** [comment]
hey, try the new version 0.14.0

**Comment by ndxbxrme** [comment]
sorry, forgot to merge, try version 0.15.0

**Comment by agung-wete** [comment]
ok, testing

**Comment by agung-wete** [comment]
:+1: , faster than before
