### ISSUE TITLE
SCSS Errors

### ISSUE THREAD

**Issue by datnordstrom** [ndxbxrme/generator-angular-meteor#18]
While processing files with fourseven:scss (for target web.browser):
   /client/components/nav/nav.scss: Scss compiler error: File to read not found
   or unreadable:
   /Users/uohc/Sites/meteor/personal/{}/client/components/nav/nav.scss

   /client/components/toolbar/toolbar.scss: Scss compiler error: File to read
   not found or unreadable:
   /Users/uohc/Sites/meteor/personal/{}/client/components/toolbar/toolbar.scss

   /client/about/about.scss: Scss compiler error: File to read not found or
   unreadable: /Users/uohc/Sites/meteor/personal/{}/client/about/about.scss

Getting errors when scss files are empty. Had to write in some scss to make it run on init.

**Comment by ndxbxrme** [comment]
hey datnordstrom
thanks for the report, I'll look into that now

**Comment by ndxbxrme** [comment]
check out v0.18.1
