### ISSUE TITLE
Meteor throws error when compiling due to dashes ('-') when providing name in camelCase

### ISSUE THREAD

**Issue by mjoldic** [ndxbxrme/generator-angular-meteor#2]
When running the generator with a name that's in camel case, it generates the objects with dashes in the name. 

yo angular-meteor:route testItems would generate the corresponding files as test-item.model.js, etc. The dashes cause Meteor to fail when compiling.

```
=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While building the application:
   model/test-item.model.js:4:30: Unexpected token -

=> Your application has errors. Waiting for file change.
```

**Comment by ndxbxrme** [comment]
html with js?

**Comment by ndxbxrme** [comment]
That should be fixed now, please give it all a good test and let me know
