### ISSUE TITLE
unable to select javascript 

### ISSUE THREAD

**Issue by kunwarVivek** [ndxbxrme/generator-angular-meteor#27]
On windows, while using the generator to create a new app, I am unable to select "javascript" as the script language. By default " Coffee script" is a selected and it is not possible to change at all.

**Comment by ndxbxrme** [comment]
hey kunwar,
it works for me...
![image](https://cloud.githubusercontent.com/assets/8391259/11238131/90cbd7ee-8ddb-11e5-9777-d227aeff5889.png)
using the up arrow.
what exactly happens when you try to select Javascript?

**Comment by kunwarVivek** [comment]
Yep, even I am surprised. It just doesn't work for the "javascript" option.
For the rest of the choices, I am able to traverse using up and down arrow
keys. Ex: in the attached screen below, I could select HTML instead of jade
for markup.

.[image: Inline image 1]

Kunwar
+91-9980915147
CamBuzz - Stay connected, Stay informed!
https://play.google.com/store/apps/details?id=com.kapish.buzz

**Comment by ndxbxrme** [comment]
That really is weird.
What version of windows are you using?  I'm on windows 7.

**Comment by kunwarVivek** [comment]
I am on windows 10. Even with powershell, I am seeing the same behavior.

Is there a workaround,
- to either change the default selection in the generator to "javascript"
- or to update the configuration after the project is created and then
  re-update the project.

Kunwar
+91-9980915147

**Comment by ndxbxrme** [comment]
Can you try it with http://cmder.net/ ?
I have a few reservations about changing the default since I set it to coffeescript on purpose.
I'll try to find someone else with windows 10 to test it on.

**Comment by kunwarVivek** [comment]
Kieron,

Cmder worked like a charm.

The workaround I wanted was only for my local copy of generator but anyway
it is no longer required. Sorry for the confusion.

Thanks.

Kunwar
+91-9980915147

**Comment by ndxbxrme** [comment]
I'm glad that worked.
Cmder is awesome:)
