### ISSUE TITLE
How can I include pagination after generating the application?

### ISSUE THREAD

**Issue by yobre** [ndxbxrme/generator-angular-meteor#29]
During the generation of my app, I chose not to include pagination. But now I need it and I want to include it. How can I do?
Thanks in advance and congratulations for the excellent work.

**Comment by Svenskunganka** [comment]
You can have a look at what the generator would be generating if you would've chosen pagination. If you chose bootstrap, here's a small portion of it: [generators/app/templates/bootstrap/client/main/main.controller(js).ng.js#L5-L10](https://github.com/ndxbxrme/generator-angular-meteor/blob/master/generators/app/templates/bootstrap/client/main/main.controller%28js%29.ng.js#L5-L10)

What you want to look for is the `<% if(pagination){ %>` in the different files. This spans out in multiple files so you'd have to check through them.

The hard things to find would be the packages you require so I'll list them here for you:
`meteor add tmeasday:publish-counts angularutils:pagination@=0.9.0`
And load the pagination directive in your angular (`client/lib/app.ng.js`):

```
angular.module('appName', [
  ...
  'angularUtils.directives.dirPagination'
]);
```

**Comment by yobre** [comment]
Thank you so much @Svenskunganka  for rapid response.
I close the issue and proceed as you suggested!
yo

**Comment by ndxbxrme** [comment]
thanks Tom!

**Comment by Svenskunganka** [comment]
@yobre @ndxbxrme no problem!

@yobre It's a bit hard to read through and find everything in the generator due to the mixing of Yeoman and the actual code, so if you run into any issues in your attempt to re-implement pagination just write here and I'll gather the code you need to get it going.

**Comment by yobre** [comment]
Wow .. you really a great @Svenskunganka ! Thank you so much ... You're very kind!

**Comment by yobre** [comment]
Hi Tom,
I can still take advantage of your kindness?

I was trying to integrate this package Atmosphere (https://atmospherejs.com/dsyko/node-csv-npm https://atmospherejs.com/dsyko/node-csv-npm) for exporting CSV but I just can not figure out where to put the code.

This problem is caused my little experience with angular-meteor so forgive me for the questions you pose.

Thanks in advance for your time.

The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential material. Any review, retransmission, distribution or other use of, or taking any action in reliance upon this information by persons or entities other than the intended recipient is prohibited. If you received this message in error, please notify the sender and delete the material from any computer. 

Andrea Bresciani
andrea.bresciani@bdt.eu.com mailto:andrea.bresciani@bdt.eu.com
Big Data Technology

P Before printing, think about the environment

**Comment by Svenskunganka** [comment]
Hey Andrea! Of course, I enjoy being of help!

Looking at the package you mentioned, I can see that it is outdated and not actively maintained - so I disregard from using that.

I've actually developed a very similar function to export stored data to Excel - but CSV shouldn't be too different. But before I can help any further, I need to know some things. If you have a Gitter account, I am available for a chat at [Svenskunganka/dev](https://gitter.im/Svenskunganka/dev) which would probably be a lot smoother - you can always login with your GitHub account if you don't have an account there yet.
