### ISSUE TITLE
Generator bug save and remove

### ISSUE THREAD

**Issue by rauleburro** [ndxbxrme/generator-angular-meteor#32]
On the generator example CRUD of things, the $scope.things.save and $scope.things.remove don't work.
I resolved to implement the current documentation.

$scope.save = function() {
    if ($scope.form.$valid) {
      Things.insert($scope.newThing);
      $scope.newThing = {};
    }
  };
and
 $scope.remove = function(thing) {
    Things.remove({_id: thing._id});
  };

It would be good to update the generator with new methods of saving and deleting.

**Comment by ndxbxrme** [comment]
well spotted, i thought I'd updated them all

**Comment by ndxbxrme** [comment]
hey,
check out the latest version (v0.20.1)

**Comment by rauleburro** [comment]
Is fixed, thanks
