### ISSUE TITLE
New helpers api remove function broken on route generator with list

### ISSUE THREAD

**Issue by donedgardo** [ndxbxrme/generator-angular-meteor#33]
Remove function not working with latest update.

``` javascript
$scope.remove = function(lawyer) {
  Lawyers.remove({_id: lawyer.id);
};
```

should be `lawyer._id` instead of `lawyer.id`
Also running into warning: `overriding 'lawyersCount helper'`

**Comment by ndxbxrme** [comment]
cheers donedgardo,
i'll look in to it
