### ISSUE TITLE
New helpers api gets called indefenetly.

### ISSUE THREAD

**Issue by donedgardo** [ndxbxrme/generator-angular-meteor#34]
``` javascript
$scope.helpers({
  saveLawyer: function(){
    return Lawyer.insert({'name':'testinghelper');
  }
});
```

I keep getting this waring `1001 overriding 'saveLawyer helper'`
the 1001 is a counter that keeps going up.

Also now i have 1001 documents inserted into Lawyers collection.
And I am not calling the helper anywhere else.

**Comment by ndxbxrme** [comment]
I don't think you should put your save function inside $scope.helpers, a lot of crazy magic happens in there.

``` javascript
$scope.helpers({
  lawyers: function() {
    //fetch function for lawyers
  }
});

$scope.saveLawyer = function() {
  Lawyer.insert({name: 'testinghelper'});
};
```

should do it

**Comment by donedgardo** [comment]
Great, works like a charm thanks for the quick response.
