### ISSUE TITLE
Versions of components

### ISSUE THREAD

**Issue by eric-2d** [ndxbxrme/generator-angular-meteor#35]
Thanks for making this, works great so far.

How do I know which versions of the 'bricks' are installed?
I'm trying to use the components from ui-boostrap but can't get a drop down or a date picker to open.
I'm probably reading the wrong version of the docs

Here's my setup:

  {
    "generator-angular-meteor": {
      "filters": {
        "js": true,
        "html": true,
        "css": true,
        "pagination": true,
        "framework": "bootstrap",
        "bower": false,
        "auth": true,
        "appname": "baldrApp",
        "projectname": "baldr",
        "modules": "'angular-meteor',\n  'ui.router',\n  'ui.bootstrap',\n      'angularUtils.directives.dirPagination',\n  'accounts.ui'",
        "usedBower": true
      },
      "appname": "testApp"
    }
  }

**Comment by eric-2d** [comment]
I think I found the versions in `.meteor/versions`

However how I can update
`angularui:angular-ui-bootstrap@0.13.0`
to the latest version (1.1.2)?

**Comment by ndxbxrme** [comment]
hey eric,
the generator should use the latest available versions.
you can force a version of a package using

```
meteor add angularui:angular-ui-bootstrap@=1.1.2
```

but i've just tried that and i get a version doesn't exist error.

i've tested making a blank regular meteor project and adding ui-bootstrap to it

```
meteor create myproject
cd myproject
meteor add angularui:angular-ui-bootstrap
```

and the version that gets installed is 0.13.0.

i think that must be the latest version in atmosphere.

the dropdown and datepicker should work, maybe something else is wrong.

i'll do some more testing

**Comment by eric-2d** [comment]
hey kieron

Don't worry about it, I got it working after figuring out the version and reading the appropriate doc. So all good.

Weird that there is such a big gap in versions though.

Thanks for the help and extra info!
