### ISSUE TITLE
Option for less and scss generator

### ISSUE THREAD

**Issue by sireskay** [ndxbxrme/generator-angular-meteor#8]
Hello, thanks for the hard work. I am willing to help with all of my requests if possible. 

Could there be an option for scss and less? I am using some premium admin template and some uses scss while other use less.

**Comment by ndxbxrme** [comment]
Hey,

I intend to spend a bunch of this weekend refactoring the generator to make it easier for other people to contribute to.  I'll try to add less, scss and initialization while I'm at it.  I'll probably need some help testing those.

At the moment I'm really looking for someone that can help to add Typescript support.

**Comment by ndxbxrme** [comment]
Less & SCSS added:)
Can you test it with your admin templates and let me know how you get on?

**Comment by sireskay** [comment]
Thanks will give it a try!

**Comment by ndxbxrme** [comment]
`npm update generator-angular-meteor` should do it

**Comment by sireskay** [comment]
quick update, got this error Scss compiler error: invalid top-level expression

**Comment by ndxbxrme** [comment]
which options did you choose?

**Comment by sireskay** [comment]
The error might be because the script writes "ECHO is off." on the first line of the app.scss file after the initial application creation. Everything works well with scss. 

I chose the Scss option, and now testing out the less portion. I am also doing this with angular-material as an option. 

it also affected app.less file once this line is deleted, the application runs as expected!

**Comment by ndxbxrme** [comment]
Ah, that was stupid of me, bad batchfile stuff:|

I'll fix it and push it in a sec.

**Comment by sireskay** [comment]
Thanks for you hard work, I love the generator, and I will be referencing your generator in a future blog post that I am about to start regarding the development with Angular-meteor. I am planning on starting an Angular-meteor meetup in Rochester Minnesota, and might reach out to you for a shout out. Thanks Again for the quick addition of this future. I an not familiar with typeScript, but will to help in any way I can!

**Comment by ndxbxrme** [comment]
I've removed the ECHOs.
Thanks for your help, glad you like the generator:)
